version: '3.8'
services:
  # Purpose: Compose file for local development.  Defines services such as
  # PostgreSQL, Redis, Minio and Nginx reverse proxy.
  # Note: Replace images and environment variables with real values when implementing.
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
      - web

  # Placeholder services for the application containers
  api:
    image: node:18-alpine
    command: node apps/api/dist/server.js
    working_dir: /workspace
    volumes:
      - ..:/workspace
    depends_on:
      - postgres
      - redis
  web:
    image: node:18-alpine
    command: serve -s apps/web/dist -l 3000
    working_dir: /workspace
    volumes:
      - ..:/workspace
    depends_on:
      - api
  worker:
    image: node:18-alpine
    command: node apps/worker/dist/worker.js
    working_dir: /workspace
    volumes:
      - ..:/workspace
    depends_on:
      - redis